name: Deploy Spring App

on:
  # main브랜치에 푸쉬가 일어나면 실행되도록 설정
  push:
    branches:
    - main  
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "./build/libs/*"
        target: "/home/ohy/workspace/web/build/libs"
        script: |
          sudo systemctl restart spring_web
