name: Deploy Spring App

on:
  # main브랜치에 푸쉬가 일어나면 실행되도록 설정
  push:
    branches:
    - main  

jobs:
  deploy:
    # 작업환경 : Ubuntu 22.04
    runs-on: ubuntu-22.04
    
    steps:
    # git repository 소스 체크아웃
    # - name: Checkout code
    #   uses: actions/checkout@v2
      
    # ubuntu 서버에 접속하여 빌드파일을 전송하고 배포된 파일을 교체
    - name: Copy directory to server and build
      # uses: ohy0718/web@main
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWD }}
        port: ${{ secrets.SERVER_PORT }}
        # source: "./build/*"
        # target: "/home/ohy/workspace/web/build/libs"
        run: | 
          cd /home/ohy/workspace/web
          git pull origin
          ./gradlew build
          systemctl restart spring_web
