name: Deploy Spring App

on:
  push:
    branches:
    - main  # main브랜치에 푸쉬가 일어나면 실행되도록 설정

jobs:
  build:
    runs-on: ubuntu-22.04 # 작업환경 : Ubuntu 22.04
    
    steps:
    # git repository 소스 체크아웃
    - name: Checkout code
      uses: actions/checkout@v2         

    # build
    - name: build 
      run: sudo ./gradlew build
  
  deploy:
    runs-on: ubuntu-22.04 # 작업환경 : Ubuntu 22.04
    
    steps:
    # git repository 소스 체크아웃
    - name: Checkout code
      uses: actions/checkout@v2
      
    # ubuntu 서버에 접속하여 빌드파일을 전송하고 배포된 파일을 교체
    - name: Copy directory to server and build
      uses: ohy0718/web@main
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "./build/*"
        target: "/home/ohy/workspace/web/build/libs"
        script: nohup java -jar web-0.0.1-SNAPSHOT.jar &
